"""Database module for Smogon VGC stats."""

from smogon_vgc_mcp.database.queries import (
    find_by_item,
    find_by_move,
    find_by_tera_type,
    get_all_snapshots,
    get_counters_for,
    get_dex_ability,
    get_dex_item,
    get_dex_move,
    get_dex_pokemon,
    get_moves_by_type,
    get_pokedex_stats,
    get_pokemon_by_type,
    get_pokemon_learnset,
    get_pokemon_stats,
    get_pokemon_type_matchups,
    get_snapshot,
    get_team,
    get_team_count,
    get_team_pokemon_count,
    get_teammates,
    get_teams_with_core,
    get_tournament_ev_spreads,
    get_type_effectiveness,
    get_usage_rankings,
    search_dex_abilities,
    search_dex_items,
    search_dex_moves,
    search_dex_pokemon,
    search_pokemon,
    search_teams,
)
from smogon_vgc_mcp.database.schema import get_db_path, init_database

__all__ = [
    "init_database",
    "get_db_path",
    "get_snapshot",
    "get_pokemon_stats",
    "get_usage_rankings",
    "search_pokemon",
    "get_teammates",
    "find_by_item",
    "find_by_move",
    "find_by_tera_type",
    "get_counters_for",
    "get_all_snapshots",
    # Team queries
    "get_team",
    "search_teams",
    "get_tournament_ev_spreads",
    "get_teams_with_core",
    "get_team_count",
    "get_team_pokemon_count",
    # Pokedex queries
    "get_dex_pokemon",
    "search_dex_pokemon",
    "get_pokemon_by_type",
    "get_dex_move",
    "search_dex_moves",
    "get_moves_by_type",
    "get_pokemon_learnset",
    "get_dex_ability",
    "search_dex_abilities",
    "get_dex_item",
    "search_dex_items",
    "get_type_effectiveness",
    "get_pokemon_type_matchups",
    "get_pokedex_stats",
]
