"""Static list of Champions Pokemon and their known Mega forms.

Pokemon Champions launched April 8, 2026 with a curated 201-Pokemon dex
(169 base species + 32 Mega forms). This list drives the Serebii fetch loop.

Each entry is (slug, serebii_dex_number) where slug is the URL-safe name
used in Serebii URLs: https://www.serebii.net/champions/pokemon/<slug>.shtml
"""

# fmt: off
# Base species: (slug, national_dex_number)
# Ordered by National Dex number for readability.
BASE_POKEMON: list[tuple[str, int]] = [
    ("bulbasaur", 1),
    ("ivysaur", 2),
    ("venusaur", 3),
    ("charmander", 4),
    ("charmeleon", 5),
    ("charizard", 6),
    ("squirtle", 7),
    ("wartortle", 8),
    ("blastoise", 9),
    ("butterfree", 12),
    ("beedrill", 15),
    ("pidgeot", 18),
    ("raticate", 20),
    ("arcanine", 59),
    ("alakazam", 65),
    ("machamp", 68),
    ("golem", 76),
    ("slowbro", 80),
    ("magneton", 82),
    ("gengar", 94),
    ("kangaskhan", 115),
    ("pinsir", 127),
    ("tauros", 128),
    ("gyarados", 130),
    ("lapras", 131),
    ("eevee", 133),
    ("vaporeon", 134),
    ("jolteon", 135),
    ("flareon", 136),
    ("aerodactyl", 142),
    ("snorlax", 143),
    ("articuno", 144),
    ("zapdos", 145),
    ("moltres", 146),
    ("dragonite", 149),
    ("mewtwo", 150),
    ("mew", 151),
    ("typhlosion", 157),
    ("feraligatr", 160),
    ("meganium", 154),
    ("ampharos", 181),
    ("bellossom", 182),
    ("marill", 183),
    ("azumarill", 184),
    ("politoed", 186),
    ("jumpluff", 189),
    ("espeon", 196),
    ("umbreon", 197),
    ("slowking", 199),
    ("misdreavus", 200),
    ("wobbuffet", 202),
    ("heracross", 214),
    ("houndoom", 229),
    ("kingdra", 230),
    ("donphan", 232),
    ("porygon2", 233),
    ("stantler", 234),
    ("smeargle", 235),
    ("miltank", 241),
    ("blissey", 242),
    ("raikou", 243),
    ("entei", 244),
    ("suicune", 245),
    ("tyranitar", 248),
    ("lugia", 249),
    ("ho-oh", 250),
    ("celebi", 251),
    ("blaziken", 257),
    ("swampert", 260),
    ("sceptile", 254),
    ("gardevoir", 282),
    ("sableye", 302),
    ("mawile", 303),
    ("aggron", 306),
    ("medicham", 308),
    ("manectric", 310),
    ("sharpedo", 319),
    ("camerupt", 323),
    ("altaria", 334),
    ("zangoose", 335),
    ("seviper", 336),
    ("absol", 359),
    ("salamence", 373),
    ("metagross", 376),
    ("latias", 380),
    ("latios", 381),
    ("kyogre", 382),
    ("groudon", 383),
    ("rayquaza", 384),
    ("jirachi", 385),
    ("deoxys", 386),
    ("empoleon", 395),
    ("infernape", 392),
    ("torterra", 389),
    ("lucario", 448),
    ("hippowdon", 450),
    ("garchomp", 445),
    ("abomasnow", 460),
    ("weavile", 461),
    ("magnezone", 462),
    ("porygon-z", 474),
    ("gallade", 475),
    ("froslass", 478),
    ("uxie", 480),
    ("mesprit", 481),
    ("azelf", 482),
    ("dialga", 483),
    ("palkia", 484),
    ("heatran", 485),
    ("regigigas", 486),
    ("giratina", 487),
    ("cresselia", 488),
    ("phione", 489),
    ("manaphy", 490),
    ("darkrai", 491),
    ("shaymin", 492),
    ("arceus", 493),
    ("serperior", 497),
    ("emboar", 500),
    ("samurott", 503),
    ("audino", 531),
    ("krookodile", 553),
    ("chandelure", 609),
    ("haxorus", 612),
    ("beartic", 614),
    ("hydreigon", 635),
    ("volcarona", 637),
    ("cobalion", 638),
    ("terrakion", 639),
    ("virizion", 640),
    ("tornadus", 641),
    ("thundurus", 642),
    ("reshiram", 643),
    ("zekrom", 644),
    ("landorus", 645),
    ("kyurem", 646),
    ("keldeo", 647),
    ("meloetta", 648),
    ("genesect", 649),
    ("chesnaught", 652),
    ("delphox", 655),
    ("greninja", 658),
    ("talonflame", 663),
    ("sylveon", 700),
    ("goodra", 706),
    ("aegislash", 681),
    ("diancie", 719),
    ("hoopa", 720),
    ("volcanion", 721),
    ("decidueye", 724),
    ("incineroar", 727),
    ("primarina", 730),
    ("lycanroc", 745),
    ("wishiwashi", 746),
    ("mimikyu", 778),
    ("kommo-o", 784),
    ("tapu-koko", 785),
    ("tapu-lele", 786),
    ("tapu-bulu", 787),
    ("tapu-fini", 788),
    ("solgaleo", 791),
    ("lunala", 792),
    ("nihilego", 793),
    ("buzzwole", 794),
    ("pheromosa", 795),
    ("xurkitree", 796),
    ("celesteela", 797),
    ("kartana", 798),
    ("guzzlord", 799),
    ("necrozma", 800),
    ("magearna", 801),
    ("marshadow", 802),
    ("naganadel", 804),
    ("stakataka", 805),
    ("blacephalon", 806),
    ("zeraora", 807),
    ("meltan", 808),
    ("melmetal", 809),
    ("rillaboom", 812),
    ("cinderace", 815),
    ("inteleon", 818),
    ("drednaw", 834),
    ("corviknight", 823),
    ("toxtricity", 849),
    ("centiskorch", 851),
    ("alcremie", 869),
    ("duraludon", 884),
    ("urshifu", 892),
    ("zarude", 893),
    ("calyrex", 898),
]

# Mega forms: (slug, national_dex_number, base_slug)
# slug is used in Serebii URLs for the Mega page.
MEGA_POKEMON: list[tuple[str, int, str]] = [
    ("venusaur-mega", 3, "venusaur"),
    ("charizard-mega-x", 6, "charizard"),
    ("charizard-mega-y", 6, "charizard"),
    ("blastoise-mega", 9, "blastoise"),
    ("alakazam-mega", 65, "alakazam"),
    ("gengar-mega", 94, "gengar"),
    ("kangaskhan-mega", 115, "kangaskhan"),
    ("pinsir-mega", 127, "pinsir"),
    ("gyarados-mega", 130, "gyarados"),
    ("aerodactyl-mega", 142, "aerodactyl"),
    ("mewtwo-mega-x", 150, "mewtwo"),
    ("mewtwo-mega-y", 150, "mewtwo"),
    ("ampharos-mega", 181, "ampharos"),
    ("heracross-mega", 214, "heracross"),
    ("houndoom-mega", 229, "houndoom"),
    ("tyranitar-mega", 248, "tyranitar"),
    ("blaziken-mega", 257, "blaziken"),
    ("swampert-mega", 260, "swampert"),
    ("sceptile-mega", 254, "sceptile"),
    ("gardevoir-mega", 282, "gardevoir"),
    ("sableye-mega", 302, "sableye"),
    ("mawile-mega", 303, "mawile"),
    ("aggron-mega", 306, "aggron"),
    ("medicham-mega", 306, "medicham"),
    ("manectric-mega", 310, "manectric"),
    ("sharpedo-mega", 319, "sharpedo"),
    ("camerupt-mega", 323, "camerupt"),
    ("altaria-mega", 334, "altaria"),
    ("absol-mega", 359, "absol"),
    ("salamence-mega", 373, "salamence"),
    ("metagross-mega", 376, "metagross"),
    ("latias-mega", 380, "latias"),
    ("latios-mega", 381, "latios"),
    ("rayquaza-mega", 384, "rayquaza"),
    ("diancie-mega", 719, "diancie"),
    ("lucario-mega", 448, "lucario"),
    ("abomasnow-mega", 460, "abomasnow"),
    ("garchomp-mega", 445, "garchomp"),
    ("gallade-mega", 475, "gallade"),
    ("audino-mega", 531, "audino"),
    ("slowbro-mega", 80, "slowbro"),
]
# fmt: on

# Convenience: all Pokemon (base + Mega)
ALL_POKEMON: list[tuple[str, int]] = [(slug, num) for slug, num in BASE_POKEMON] + [
    (slug, num) for slug, num, _ in MEGA_POKEMON
]

# Lookup: base_slug -> list of mega_slugs
MEGA_FORMS: dict[str, list[str]] = {}
for _mega_slug, _mega_num, _base_slug in MEGA_POKEMON:
    MEGA_FORMS.setdefault(_base_slug, []).append(_mega_slug)
